In [16]:
import pandas as pd
import numpy as np
Data={'Names':['Cool','Silent','Decent',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['hyd','gnt',np.nan,'nrt']}


df=pd.DataFrame(Data)
df

Names   Age City
0    Cool   NaN  hyd
1  Silent  22.0  gnt
2  Decent  25.0  NaN
3     NaN  27.0  nrt

In [6]:
import pandas as pd
import numpy as np
Data={'Names':['Cool','Silent','Decent',None],
      'Age':[None,22,25,27],
      'City':['hyd','gnt',None,'nrt']}


df2=pd.DataFrame(Data)
df2

Names   Age  City
0    Cool   NaN   hyd
1  Silent  22.0   gnt
2  Decent  25.0  None
3    None  27.0   nrt

In [5]:
import pandas as pd
import numpy as np
Data={'Names':['Cool','Silent','Decent'],
      'Age':[22,25,27],                                # Here Null is a variable.
      'City':['hyd','gnt','nrt']}


df3=pd.DataFrame(Data)
df3

Names  Age City
0    Cool   22  hyd
1  Silent   25  gnt
2  Decent   27  nrt

In [12]:
df2.dtypes

Names     object
Age      float64
City      object
dtype: object

In [14]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [ ]:
df.read_csv('Missing_value.csv',index=False)

In [20]:
df.isnull().sum()         # it will provide the how many missing values are there

Names    1
Age      1
City     1
dtype: int64

**fillna**

In [23]:
df.fillna(30)   #in the dataframe whereever the null it will gives 30.

Names   Age City
0    Cool  30.0  hyd
1  Silent  22.0  gnt
2  Decent  25.0   30
3      30  27.0  nrt

In [28]:
df['Age'].fillna(30)         # it will specify the specific column.

0    30.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

- the above one is we are filling randomly
- all the columns are filled with random number
- it is not a good approach because in a data we have different data types

**What is the difference between np.nan and None**

In [29]:
np.nan+5

nan

In [30]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [35]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,np.nan,3])

In [36]:
arr1

array([ 1.,  2., nan,  3.])

In [37]:
arr2

array([ 1.,  2., nan,  3.])

In [40]:
np.nansum(arr1),np.sum(arr1)

(np.float64(6.0), np.float64(nan))

In [41]:
np.nansum(arr2),np.sum(arr2)

(np.float64(6.0), np.float64(nan))

In [42]:
np.sum(arr2)

np.float64(nan)

- np.nan represents **float type**
- None represents **Object type**
- if data operations related to Maths than nan format is better

**Fill the value based on column**

In [43]:
df['Names'].fillna('Style')

0      Cool
1    Silent
2    Decent
3     Style
Name: Names, dtype: object

**Fill with methods**

- whenever we are using methods no need provide values.

In [44]:
import pandas as pd
import numpy as np
Data={'Names':['Cool','Silent','Decent',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['hyd','gnt',np.nan,'nrt']}


df=pd.DataFrame(Data)
df

Names   Age City
0    Cool   NaN  hyd
1  Silent  22.0  gnt
2  Decent  25.0  NaN
3     NaN  27.0  nrt

- pad
- bfill
- ffill
- backfill

In [46]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')

Names   Age City
0    Cool   NaN  hyd
1  Silent  22.0  gnt
2  Decent  25.0  gnt
3  Decent  27.0  nrt

In [47]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='bfill')

Names   Age City
0    Cool  22.0  hyd
1  Silent  22.0  gnt
2  Decent  25.0  nrt
3     NaN  27.0  nrt

In [51]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='ffill')

Names   Age City
0    Cool   NaN  hyd
1  Silent  22.0  gnt
2  Decent  25.0  gnt
3  Decent  27.0  nrt

In [49]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='backfill')

Names   Age City
0    Cool  22.0  hyd
1  Silent  22.0  gnt
2  Decent  25.0  nrt
3     NaN  27.0  nrt

In [56]:
age_median=df['Age'].median()
df['Age'].fillna(age_median)

0    25.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [57]:
age_mean=df['Age'].mean()
df['Age'].fillna(age_mean)

0    24.666667
1    22.000000
2    25.000000
3    27.000000
Name: Age, dtype: float64

In [58]:
age_mode=df['Age'].mode()
df['Age'].fillna(age_mode)

0    22.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

**KNN Immputer**

- K-Nearest Neighbours
- where k = hyper parameter which means the user can change
- idea:Instead of taking all the samples average
    - First fix the neighbours number i.e.k
    - Then find the neighbours using distance metric
    - Then take the average of those samples to fill the missing values

In [ ]:
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer

In [3]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
x=[[1,2,np.nan],[4,np.nan,6],[np.nan,7,8],[9,3,5]]
pd.DataFrame(x)

0    1    2
0  1.0  2.0  NaN
1  4.0  NaN  6.0
2  NaN  7.0  8.0
3  9.0  3.0  5.0

In [9]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
x=[[1,2,np.nan],[4,np.nan,6],
   [np.nan,7,8],[9,3,5]]
imputer=KNNImputer(n_neighbors=2,
                   weights='uniform')  
imputer.fit_transform(x)

array([[1. , 2. , 7. ],
       [4. , 4.5, 6. ],
       [6.5, 7. , 8. ],
       [9. , 3. , 5. ]])